### ISSUE TITLE
Move this repo to the new WFDB organisation?

### ISSUE THREAD

**Issue by tompollard** [wfdb/mimic_wfdb_tutorials#4]
We now have a dedicated GitHub organisation for WFDB: https://github.com/wfdb. Should we move these workshop materials to this new organisation?

I think there are benefits to moving the repo, most of which relate to the fact that the content more closely aligns with WFDB than LCP (more logical place to look for the repo, easier to find for people browsing WFDB materials, etc).

If we are moving the repo, it makes sense to move it sooner rather than later (mainly to avoid propagation of incorrect links, even if GitHub does do a good job at forwarding them).

**Comment by peterhcharlton** [comment]
Great - yes, let's move it over to the wfdb organisation. I'll put in a request to move it over shortly, after I've resolved some of the other edits and got the Python code working again.

**Comment by peterhcharlton** [comment]
Please do move the repo to the WFDB organisation. Thanks

**Comment by tompollard** [comment]
@peterhcharlton @bemoody @briangow The WFDB tutorial repository has been moved to https://github.com/wfdb/

**Comment by tompollard** [comment]
@peterhcharlton you should be able to switch your local repo to the new GitHub location with:

```
# view your remotes
git remote --v

# remove the old location
git remote rm origin

# add the new location
git remote add origin git@github.com:wfdb/mimic_wfdb_tutorials.git
```
