### ISSUE TITLE
wfdb.io is expired

### ISSUE THREAD

**Issue by Zoew420** [wfdb/mimic_wfdb_tutorials#86]
Hi, I am interested in learning from a tutorial, but I have found that the domain name of your website [wfbd.io](wfbd.io) has expired and is inaccessible. May I know if there are any other convenient tools or addresses available for me to read the tutorial?

**Comment by peterhcharlton** [comment]
Agreed - perhaps we could move the GitHub pages hosting from this domain back to the usual GitHub domain?

**Comment by Zoew420** [comment]
> I'm waiting to hear back from Chen about the domain. I'd like to keep the domain, or move to something similar that is hosted by the lab.

Thank you very much for maintaining this domain. I can now access the tutorial website and study normally. Thank you.
